services:
  poetry:
    image: deanayalon/poetry
    build: 
      tags: [ghcr.io/deanayalon/poetry]
      platforms:
        - linux/amd64
        - linux/arm64/v8

  dev:
    image: deanayalon/poetry:dev
    build: .
    develop:
      watch:
        - path: dockerfile
          action: rebuild