FROM deanayalon/poetry AS deps
# Python dependencies
COPY pyproject.toml poetry.lock ./
RUN poetry install

FROM python:3.12-bookworm-slim

WORKDIR /app
ENV PATH="/app/.venv/bin:$PATH"
COPY --from=deps /app/.venv ./.venv

# COPY SCRIPTS

ENTRYPOINT ["python3", ""]
# python3 main.py